Repository atviriduomenys/manifest, pull requests merged in 2022-09, with the labels that each got.

#1521 1230 georeferencinio pagrindo kadastras
  datasets/gov/giscentras/grpk.csv
  get_data_gov_lt.in
Labels: gis-centras, centralizuotai

#1572 Verslo liūdijimų duomenų rinkinys
  datasets/gov/vmi/verslo_liudijimai.csv
Labels: valstybinė mokesčių inspekcija, centralizuotai

#1578 Create geologija_zemes_istekliai
  datasets/gov/lgt/geologija_zemes_istekliai
Labels: lietuvos geologijos tarnyba

#1574 Create svietimo_istaigos.csv
  datasets/gov/lsd/svietimo_istaigos.csv
Labels: lietuvos statistikos departamentas, centralizuotai

#1589 Švietimo institucijos update
  datasets/gov/lsd/svietimo_istaigos.csv
Labels: lietuvos statistikos departamentas, centralizuotai

#1580 geologiniai tyrimai
  datasets/gov/lgt/geologiniai_tyrimai.csv
Labels: lietuvos geologijos tarnyba
