Repository atviriduomenys/manifest, pull requests merged in 2022-07, with the labels that each got.

#1527 Update imoniu_bankrotas.csv
  datasets/gov/avnt/imoniu_bankrotas.csv
Labels: centralizuotai, audito tarnyba

#1528 Update imoniu_restrukturizavimas.csv
  datasets/gov/avnt/imoniu_restrukturizavimas.csv
Labels: centralizuotai, audito tarnyba

#1530 Update imoniu_restrukturizavimas.csv
  datasets/gov/avnt/imoniu_restrukturizavimas.csv
Labels: centralizuotai, audito tarnyba

#1529 Update imoniu_bankrotas.csv
  datasets/gov/avnt/imoniu_bankrotas.csv
Labels: centralizuotai, audito tarnyba

#1533 Update covid19.csv
  datasets/gov/lsd/covid19.csv
Labels: lietuvos statistikos departamentas

#1384 Gyventojų užimtumo statistinio tyrimo duomenų ADSA
  datasets/gov/lsd/gyventoju_uzimtumas.csv
Labels: lietuvos statistikos departamentas, centralizuotai
