Repository atviriduomenys/manifest, pull requests merged in 2022-04, with the labels that each got.

#945 Pagalvės mokestis
  datasets/gov/kaunas/pagalve.csv
  get_data_gov_lt.in
Labels: savarankiškai, kaunas

#984 Update klimatologija.csv
  datasets/gov/lhmt/klimatologija.csv
Labels: lietuvos hidrometeorologijos tarnyba, centralizuotai

#994 951 duomenys apie lietuvos pareiškėjų finansuotas paraiškas es mokslinių tyrimų ir inovacijų programose horizon horizon europe 1
  datasets/gov/mita/horizon.csv
Labels: mokslo inovacijų ir technologijų agentūra, centralizuotai

#978 Gyventojų ir būstų surašymo ADSA
  datasets/gov/lsd/gyventojai_bustas.csv
Labels: lietuvos statistikos departamentas, centralizuotai
