Repository atviriduomenys/manifest, pull requests merged in 2024-04, with the labels that each got.

#3172 Update atvykstantys_pabegeliai.csv
  datasets/gov/rppc/atvykstantys_pabegeliai.csv
Labels: Pabėgėlių priėmimo centras

#3085 Vstt kadastras cleaning
  datasets/gov/vstt/saugomu_ter_kadastras.csv
Labels: valstybinė saugomų teritorijų tarnyba

#3203 ESSC AAP ADSA
  datasets/gov/essc/aspi.csv
  get_data_gov_lt.in
Labels: ekstremalių sveikatai situacijų centras

#3200 3195 jaunimo reikalų agentūros jaunimo savanoriška tarnyba
  datasets/gov/jra/paraiskos.csv
  get_data_gov_lt.in
Labels: Jaunimo reikalų agentūra

#3201 3196 jaunimo reikalų agentūros jaunimo darbuotojai
  datasets/gov/jra/kvalifikacija.csv
  get_data_gov_lt.in
Labels: Jaunimo reikalų agentūra

#3202 VULŽK MEDDREAM ADSA
  datasets/gov/vulzk/meddream.csv
  get_data_gov_lt.in
Labels: Vilniaus universiteto ligoninės Žalgirio klinika

#3212 3211-vulžk-meddream
  datasets/gov/vulzk/meddream.csv
Labels: Vilniaus universiteto ligoninės Žalgirio klinika

#3218 Add files via upload
  datasets/gov/gtc/hemosporidiniai_parazitai.csv
  get_data_gov_lt.in
Labels: gamtos tyrimų centras

#3231 3211-vulžk-meddream-1
  datasets/gov/vulzk/meddream.csv
Labels: Vilniaus universiteto ligoninės Žalgirio klinika

#3229 3227-ukmergės-lig-jivex
  datasets/gov/ukmlig/jivex.csv
  get_data_gov_lt.in
Labels: Ukmergės ligoninė

#3224 LKD laisvės atėmimo ADSA
  datasets/gov/lkd/laisves_atemimas.csv
  get_data_gov_lt.in
Labels: kalėjimų departamentas

#3223 LKD areštų ADSA
  datasets/gov/lkd/arestai.csv
  get_data_gov_lt.in
Labels: kalėjimų departamentas

#3248 3221-lietuvos-kalėjimų-departamento-nuteistųjų-laisvės-atėmimu-dvd-1
  datasets/gov/lkd/laisves_atemimas.csv
Labels: kalėjimų departamentas

#3244 3196-jaunimo-reikalų-agentūros-jaunimo-darbuotojai-1
  datasets/gov/jra/kvalifikacija.csv
Labels: Jaunimo reikalų agentūra

#3243 3198-essc-aspį-ekstremalių-situacijų-planų-vertinimai-1
  datasets/gov/essc/spi.csv
Labels: ekstremalių sveikatai situacijų centras

#3246 3240 pasienio kontrolės punktų direkcija evis
  datasets/gov/pkpd/evis.csv
  get_data_gov_lt.in
Labels: Pasienio kontrolės punktų direkcija

#3252 3251 gamtos tyrim centro dirvoemio temperatros ir drgms matavimai
  datasets/gov/gtc/dirvozemio_temperatura.csv
  get_data_gov_lt.in
Labels: gamtos tyrimų centras

#3253 3240-pasienio-kontrolės-punktų-direkcija-evis-1
  datasets/gov/pkpd/evis.csv
Labels: Pasienio kontrolės punktų direkcija
