Repository atviriduomenys/manifest, pull requests merged in 2024-11, with the labels that each got.

#3779 3778 marijampols cs objektai
  datasets/gov/marijampoles_sav/cs_objektai.csv
  get_data_gov_lt.in
Labels: Marijampolės savivaldybės administracija

#3784 Update augalu_fenologija.csv
  datasets/gov/lhmt/augalu_fenologija.csv
Labels: lietuvos hidrometeorologijos tarnyba

#3796 Update vaistiniai_preparatai.csv
  datasets/gov/vvkt/vaistiniai_preparatai.csv
Labels: Valstybinė vaistų kontrolės tarnyba

#3831 3830 pacientų kuriems diagnozuota tuberkuliozė žalingi įpročiai
  datasets/gov/santara/tub_pacientu_zalingi_iprociai.csv
  get_data_gov_lt.in
Labels: santaros klinikos

#3835 3834 sppd sglep
  datasets/gov/sppd/soc_globos_licencijos.csv
  get_data_gov_lt.in
Labels: socialinių paslaugų priežiūros departamentas

#3846 3845 zuvininkystes tarnyba ptr
  datasets/gov/ztzum/verslines_zvejybos_kvotos.csv
  get_data_gov_lt.in
Labels: zuvininkystes tarnyba

#3844 3840 pagd vppvais
  datasets/gov/pagd/statinio_patikrinimas/statinio_patikrinimas.csv
  get_data_gov_lt.in
Labels: priešgaisrinės apsaugos ir gelbėjimo departamentas

#3872 3845 zuvininkystes tarnyba ptr upd
  datasets/gov/ztzum/verslines_zvejybos_kvotos.csv
Labels: zuvininkystes tarnyba

#3871 3870 klaipėdos prekybos leidimai
  datasets/gov/klaipedos_m_sav/prekybos_leidimai.csv
  get_data_gov_lt.in
Labels: Klaipėdos miesto savivaldybės administracija

#3880 Update prekybos_leidimai.csv
  datasets/gov/klaipedos_m_sav/prekybos_leidimai.csv
Labels: Klaipėdos miesto savivaldybės administracija
