Repository atviriduomenys/manifest, pull requests merged in 2024-06, with the labels that each got.

#3356 Create aktualiu_adresu_gardeles.csv
  datasets/gov/lsd/aktualiu_adresu_gardeles.csv
  get_data_gov_lt.in
Labels: lietuvos statistikos departamentas, registrų centras

#3347 3346 rokiškio raj lig openlims
  datasets/gov/rokiskio_r_lig/openlims.csv
  get_data_gov_lt.in
Labels: Rokiškio rajono ligoninė

#3345 MML sLIS ADSA
  datasets/gov/mml/slis.csv
  get_data_gov_lt.in
Labels: Mykolo Marcinkevičiaus ligoninė
