Repository atviriduomenys/manifest, pull requests merged in 2024-07, with the labels that each got.

#3372 3371 panevio miesto tarybos posdi balsavim rezultatai
  datasets/gov/panevezio_m_sav/balsavimai.csv
  get_data_gov_lt.in
Labels: Panevėžio miesto savivaldybė

#3378 3377 muitins prievolinink registras
  datasets/gov/muitine/muitines_prievolininkai.csv
  get_data_gov_lt.in
Labels: muitinės departamentas

#3404 3403 palangos gintaras psutsuteiktos paslaugos
  datasets/gov/palangos_gintaras/suteiktos_paslaugos.csv
  get_data_gov_lt.in
Labels: Palangos gintaras

#3416 3415 leidimai naudoti orlaivų stotis
  datasets/gov/rrt/leid_orlaiviu_stotys.csv
  get_data_gov_lt.in
Labels: ryšių reguliavimo tarnyba

#3418 3417 leidimai naudoti laivų stotis
  datasets/gov/rrt/leid_laivu_stotys.csv
  get_data_gov_lt.in
Labels: ryšių reguliavimo tarnyba

#3420 3419 radijo mėgėjams išduoti leidimai
  datasets/gov/rrt/leid_radijo_megejai.csv
  get_data_gov_lt.in
Labels: ryšių reguliavimo tarnyba

#3422 3421 domenai su lietuvos vardu
  datasets/gov/rrt/domenai_su_lt_vardu.csv
  get_data_gov_lt.in
Labels: ryšių reguliavimo tarnyba

#3424 3423 elektroninių ryšių paslaugų bei pašto paslaugos teikėjai ir jų pateiktų periodinių ataskaitų statistika
  datasets/gov/rrt/el_rysiu_ir_pasto_teikejai.csv
  get_data_gov_lt.in
Labels: ryšių reguliavimo tarnyba
