Repository atviriduomenys/manifest, pull requests merged in 2024-05, with the labels that each got.

#3255 3254 vlkk terminų bankas
  datasets/gov/vlkk/lrtb.csv
  get_data_gov_lt.in
Labels: Valstybinė lietuvių kalbos komisija

#3263 3261-vulžk-medis
  datasets/gov/vulzk/medis.csv
  get_data_gov_lt.in
Labels: Vilniaus universiteto ligoninės Žalgirio klinika

#3259 Update matininkai.csv
  datasets/gov/nzt/matininkai.csv
Labels: nacionalinė žemės tarnyba

#3265 3264-vulžk-žkis
  datasets/gov/vulzk/zkis.csv
  get_data_gov_lt.in
Labels: Vilniaus universiteto ligoninės Žalgirio klinika

#3270 3267 marijampoles savivaldybes sistema medziai
  datasets/gov/Marijampoles_sav/leidimas_kirsti.csv
  get_data_gov_lt.in
Labels: Marijampolės savivaldybės administracija

#3278 VLKK vardų IS ADSA
  datasets/gov/vlkk/vardai.csv
  get_data_gov_lt.in
Labels: Valstybinė lietuvių kalbos komisija

#3292 3261 vulžk registracija
  datasets/gov/vulzk/registracija.csv
  get_data_gov_lt.in
Labels: Vilniaus universiteto ligoninės Žalgirio klinika

#3288 3264 vulžk žkis 1
  datasets/gov/vulzk/zkis.csv
Labels: Vilniaus universiteto ligoninės Žalgirio klinika

#3225 LKD kalinamų asmenų ADSA
  datasets/gov/lkd/laikomi_asmenys.csv
  get_data_gov_lt.in
Labels: kalėjimų departamentas

#3316 3315 klaipdos r apklaus sistema
  datasets/gov/klaipedos_r_sav/apklausu_sistema.csv
  get_data_gov_lt.in
Labels: Klaipėdos rajono savivaldybė
