Repository atviriduomenys/manifest, pull requests merged in 2025-07, with the labels that each got.

#4359 Update bibliografiniai_irasai.csv
  datasets/gov/lab/bibliografiniai_irasai.csv
Labels: lietuvos statistikos departamentas, Lietuvos audiosensorinė biblioteka

#4360 Update and rename infostatyba.csv folder change from vtpsi to ssva
  datasets/gov/ssva/infostatyba.csv
  get_data_gov_lt.in
Labels: Statybos sektoriaus vystymo agentūra

#4375 KedainiuSav
  datasets/gov/tvs/sutartys.csv
  datasets/gov/tvs/turtas.csv
Labels: Turto valdymo sistema

#4393 4391 pasipriešinimo okupacijoms dalyviai
  datasets/gov/lggrtc/pasipriesinimo_okupacijoms_dalyviai.csv
  get_data_gov_lt.in
Labels: LGGRTC
