Repository atviriduomenys/manifest, pull requests merged in 2025-08, with the labels that each got.

#4419 4418 sveikatos priežiūros specialistų kompetencijų duomenys
  datasets/gov/vaspvt/specialistu_kompetencijos.csv
  get_data_gov_lt.in
Labels: sveikatos priežiūros akreditavimo tarnyba

#4425 4424 pacientų sergančių plaučių arterine hipertenzija gydymo duomenys
  datasets/gov/lsd/sveikata/pah_diagnozes.csv
  get_data_gov_lt.in
Labels: VDA

#4429 4428 marijampoles tvs
  datasets/gov/tvs/sutartys.csv
  datasets/gov/tvs/turtas.csv
Labels: Marijampolės savivaldybės administracija
