Repository atviriduomenys/manifest, pull requests merged in 2025-05, with the labels that each got.

#4275 Atnaujinti elektroninis_archyvas.csv: apyrašų lentelės pavadinimas
  datasets/gov/lvat/elektroninis_archyvas.csv
Labels: Lietuvos vyriausiojo archyvaro tarnyba

#4278 4234 aaa atvr upd
  datasets/gov/aaa/atlieku_tvarkytoju_valstybes_registras.csv
Labels: aplinkos apsaugos agentūra

#4280 4279 bibliografiniai įrašai
  datasets/gov/lab/bibliografiniai_irasai.csv
  get_data_gov_lt.in
Labels: lietuvos statistikos departamentas, Lietuvos audiosensorinė biblioteka

#4300 4299 valstybinės reikšmės kelių projektai
  datasets/gov/via_lietuva/keliu_projektai.csv
  get_data_gov_lt.in
Labels: VIA Lietuva
